behaviors:
  landing:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 409600
      learning_rate: 0.0003
      beta: 0.0001
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5000
    max_steps: 7000000000
    time_horizon: 1024
    summary_freq: 30000